 -  -  - 
title: "Lab Exercises 11  -  Mixture Model"
output:
  html_document: default
  html_notebook: default
 -  -  - 
 
Simulate 200 observations from a $0.25*N(10,2) + 0.75*N(15,3)$ density. Run an MCMC analysis on the data using the mixture model. What are your conclusions?

```{r SETUP, include = FALSE}
require(broom)
require(profvis)
require(data.table)


```
```{r defns, include = FALSE}
rm(list = ls())
mean2 <- function(x) sum(x)/length(x) # mean function in r is about 4
var2 <- function(x, len=length(x), sx=sum(x)) {sum(x*x)-{sx*sx/len}}/{len-1}

htfunc <- function(y,
                   kt,
                   y1set = y[kt == 1],
                   y2set = y[kt == 2],
                   n1 = length(y1set),
                   n2 = length(y2set), 
                   y1 =  y1set - sum(y1set)/n1,
                   y2 = y2set - sum(y2set)/n2)

  {-0.5*{log(n1) + log(n2)} + 
  lgamma({n1 - 1}/2) + 
  lgamma({n2 - 1}/2) - 
  {n1 - 1}/2*log(sum(y1*y1)) - 
  {n2 - 1}/2 * log(sum(y2*y2))}

n  <-  200L # number of samples (L specifies integer)
d <- 1000L    # (MCMC sample size)
pkymax <- -99999

n.vec <- vector("numeric", length=n)
d.vec <- vector("numeric",length=d)


y2 <- vector("numeric",length=0)
y3 <- vector("numeric", length=0)


ktmax <- n.vec
ktold <- n.vec
mpkty <- n.vec
pyt <- n.vec
pyt2 <- n.vec

omeg <- d.vec
omeg[1] <- rbeta(1, 1, 1) # Initialises omeg

mu1 <- d.vec
mu2 <- d.vec
sig1 <- d.vec
sig2 <- d.vec
rm(n.vec,d.vec)
```

```{r Model}
profvis({
# The following generates n samples from two different Normal distributions given 
# in the question, according to the specified mixture proportion.

  condition <- {runif(n, 0, 1)  < 0.25}
  y  <-  rnorm(n, 15, sqrt(3)) # Initialises y

for(t in {1:n}[condition]) {
  if(condition[t]) { # 0.25 is value given in question statement for mixture prop.
    y[t]<-rnorm(1, 10, sqrt(2)) # N(10,2)
  }
}

# REMOVED - UNNESCESSARY ====
# n<-length(y)   # (for data sample)
# ====


# The following creates an initial k that we will update later.

condition <- {runif(n,0,1) > 0.5} 
kt <- c(rep(2,n)) # Initialises kt: vector that assigns each 

for(k in (1:n)[condition]) {
  if(condition[k]) { # if assigns 1/2 according to output of runif with 50% 
    kt[k]<-1 
  }
}


n1 <- length(y[kt == 1])
n2 <- n - n1
# The following updates the values in k to equalise the variance of the two groups.
 

while (var2(y[kt == 2]) > var2(y[kt == 1])) {
  condition <- {runif(n,0,1) > 0.5}
  for(k in (1:n)[condition]) {
    if(condition[k]) {
      kt[k] <- 1
    } 
  }
}


mu1[1] <- mean2(y) # mean of the initial sample
sig1[1] <- var2(y)*1.5 

mu2[1] <- mean2(y)
sig2[1] <- var2(y)*0.5
ktmax <- kt



for(j in 2:d) {
  ktold<-kt
  for(t in 1:n) {
    
    kt[t] <- 1
    ht1<- htfunc(y,kt) + log(omeg[j - 1])
    
    kt[t] <- 2
    ht2 <- htfunc(y,kt) + log(1 - omeg[j - 1])          
    
    pyk<- 1/{1 + exp(ht2 - ht1)}
    
    if(is.nan(pyk)) {
      
      if(is.nan(ht1)) {
        kt[t] <- 1
      }
      if(is.nan(ht2)) {
        kt[t] <- 2
      }
     } else {
       if(runif(1,0,1)<pyk) {
         kt[t] <- 1
         pyt2[t] <- pyt2[t]+dnorm(y[t],mu1[j-1],sqrt(sig1[j-1]))
       } else {
         kt[t] <- 2
         pyt2[t] <- pyt2[t]+dnorm(y[t],mu2[j-1],sqrt(sig2[j-1]))
       }
       
      mpkty[t] <- mpkty[t] + pyk
    }
    
    n1 <- length(y[kt == 1])
    n2 <- n - n1
    
    if (n1 < 2 | n1 > {n - 3} | var2(y[kt == 2]) > var2(y[kt == 1])) {
      kt[t] <- ktold[t]
      n1 <- length(y[kt == 1])
      n2 <- n - n1
    }
    
    pyt[t] <- pyt[t] + 
              dnorm(y[t], mu1[j-1], sqrt(sig1[j-1]))*omeg[j-1] + 
              dnorm(y[t], mu2[j-1], sqrt(sig2[j-1]))*{1 - omeg[j-1]}
  }
  
  y1 <- y[kt == 1]
  y2 <- y[kt == 2]
  
  condition <- {n1 < 2 | n1 > {n - 3} | var2(y2) > var2(y1)}
  
  if(condition) {
    kt <- ktold
    n1 <- length(y[kt == 1])
    n2 <- n - n1
  }

  
  lpyk <- htfunc(y,kt) + 
          n1*log(omeg[j-1]) + 
          n2*log(1 - omeg[j-1])
  
  if(lpyk > pkymax) {
    pkymax <- lpyk
    ktmax <- kt
  }

      

  
  mu1[j] <- rt(1, n1 - 1)*sqrt(var2(y1)/n1) + mean2(y1)
  mu2[j] <- rt(1, n2 - 1)*sqrt(var2(y2)/n2) + mean2(y2)
  
  ymu <- {y1 - mu1[j]}*{y1 - mu1[j]} # (y1 - mu1[j])^2 is slower
  D <- sum(ymu)
  
  sig1[j] <- 1/rgamma(1, n1/2, D/2)
  ymu <- {y2 - mu2[j]}*{y2 - mu2[j]} # (y2 - mu2[j])^2 is slower
  D <- sum(ymu)
  
  sig2[j] <- 1/rgamma(1,n2/2,D/2)
  
  a <- n1 + 1
  b <- n2 + 1
  omeg[j] <- rbeta(1, a, b)  
}

rm(list = setdiff(ls(),list("d","mpkty","pyt","pyt2","y")))
# Plotting the Results.

mpkty <- mpkty/d
pyt <- pyt/d
pyt2 <- pyt2/d

y.sort <- sort(y, index.return=T)


plot(y.sort$x, 
     pyt[y.sort$ix],
     type='l',
     col=4
     )
lines(density(y),
      col=2
      )
})

```
