---
title: "Lab7"
author: "Benjamin Moran"
date: "12 September 2016"
output: html_document
---
```{r Setup, echo = FALSE}
knitr::opts_chunk$set(cache = TRUE)
```

### Question 2
Consider the binomial regression example in Lecture 8.

```{r Q2}
x <- c(-0.863, -0.296, -0.053, 0.727)
n <- c(5,5,5,5)
y <- c(0,1,3,5)

bioassay <- data.frame(x = c(-0.863, -0.296, -0.053, 0.727), n = c(5,5,5,5), y = c(0,1,3,5))

summary(glm(y/n~x, data = bioassay, family = binomial, weights = n))
#Classical Intervals
beta.ulim <- 7.9128+qnorm(0.975)*5.0620
beta.llim <- 7.9128-qnorm(0.9755)*5.0620

beta.ulim
beta.llim

alpha.ulim <- 0.8734+qnorm(0.975)*1.0401
alpha.llim <- 0.8734-qnorm(0.975)*1.0401

alpha.ulim
alpha.llim
```

```{r Q2 Grid}

px <- seq(1,1000^2)
dim(px) <- c(1000,1000)
a.seq <- seq(-5,10,by=15/999)
b.seq <- seq(-3,50,by=53/999)

sy <- sum(y)
sxy <- sum(x*y)

for(k in 1:1000){
  for(j in 1:1000){
    px[k,j] = a.seq[k]*sy + b.seq[j]*sxy - 5*sum(log(1 + exp(a.seq[k] + b.seq[j]*x)))
  }
}
px3 <- px
px2 <- exp(px)
contour(a.seq,b.seq,px2)
```

```{r Q2d}
# marginal of alpha or alpha | y.
pxa <- 0
for(k in 1:1000){
  pxa[k] = sum(px2[k,])
}

pxa2 <- pxa/sum(pxa)
plot(a.seq,pxa2,type='l')

```

```{r Q2 Cond.Beta}

cdfa <- cumsum(pxa2)
plot(a.seq, cdfa, type = 'l')

u.a <- runif(5000,0,1)
a1 <- 0; b1 <- 0
for(i in 1:5000){
  st.a=0;k.a=1
  while(st.a==0){
    if(cdfa[k.a+1] > u.a[i] & cdfa[k.a] < u.a[i]){ # This finds a cond.est of alpha
      a1[i] = a.seq[k.a]; st.a=1
    } else {
      k.a = k.a + 1
    }
  } # then we pump this cond.est of alpha into a cond.est of beta.
  pxb = px2[k.a,]; pxb2 = pxb/sum(pxb); cdfb = cumsum(pxb2)
  st.b = 0; k.b = 1; u.b = runif(1,0,1)
  while(st.b==0){
    if(cdfb[k.b+1] > u.b & cdfb[k.b] < u.b){
      b1[i] = b.seq[k.b]; st.b=1
    } else {
      k.b = k.b + 1
    }
  }
}
hist(a1)
mean(a1)
quantile(a1,c(0.025,0.975))

hist(b1, 20)
mean(b1)
quantile(b1,c(0.025,0.975))
```